name: Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  OUTPUT_FOLDER: "./output"
  
jobs:
  pack-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v5

      - name: Checkout shared-gfx repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/shared-gfx
          path: shared-gfx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout hal-common repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/hal-common
          path: hal-common
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout hal-avr0-spi repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/hal-avr0-spi
          path: hal-avr0-spi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-macros repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/utils-macros
          path: utils-macros
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare library package
        run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/shared/gfx
          cp -r ./shared-gfx/color.h ./${{ env.OUTPUT_FOLDER }}/shared/gfx/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/enums
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/macros
          cp -r ./hal-common/enums/SPI_enums.h ./${{ env.OUTPUT_FOLDER }}/hal/common/enums/
          cp -r ./hal-common/macros/PORT_macros.h ./${{ env.OUTPUT_FOLDER }}/hal/common/macros/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/enums
          cp -r ./hal-common/enums/SPI_enums.h ./${{ env.OUTPUT_FOLDER }}/hal/common/enums/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/avr0/spi
          cp -r ./hal-avr0-spi/spi.c ./${{ env.OUTPUT_FOLDER }}/hal/avr0/spi/
          cp -r ./hal-avr0-spi/spi.h ./${{ env.OUTPUT_FOLDER }}/hal/avr0/spi/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/macros
          cp -r ./utils-macros/stringify.h ./${{ env.OUTPUT_FOLDER }}/utils/macros/
          
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/drivers/led/apa102
          cp ./apa102.c ./${{ env.OUTPUT_FOLDER }}/drivers/led/apa102/
          cp ./apa102.h ./${{ env.OUTPUT_FOLDER }}/drivers/led/apa102/
 
      - name: Pack files for upload
        run: |
          tar -czvf build.tar.gz ${{ env.OUTPUT_FOLDER }}
          zip -r build.zip ${{ env.OUTPUT_FOLDER }}

      - name: Upload library package
        uses: actions/upload-artifact@v4
        with:
            name: library-package
            path: ${{ env.OUTPUT_FOLDER }}
            retention-days: 1